#!/usr/bin/env bash

if
  [[ -s "/home/redmine/.rvm/gems/ruby-2.5.1/environment" ]]
then
  source "/home/redmine/.rvm/gems/ruby-2.5.1/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/redmine/.rvm/gems/ruby-2.5.1/environment'" >&2
  exit 1
fi
