#!/usr/bin/env bash

if
  [[ -s "/home/redmine/.rvm/gems/ruby-2.5.1@global/environment" ]]
then
  source "/home/redmine/.rvm/gems/ruby-2.5.1@global/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/redmine/.rvm/gems/ruby-2.5.1@global/environment'" >&2
  exit 1
fi
